#/bin/bash

kopt="${-}"

set +u
set -e

if [ -z "${VENTI_HOME}" ]; then
	VENTI_HOME="$(realpath "$(( [ -n "${BASH_SOURCE}" ] && dirname "$(realpath "${BASH_SOURCE[0]}")" ) || dirname "$(realpath "${0}")")""/../../../../..")"
fi

set -u

CROSS_COMPILE_SYSTEM='dragonfly'
CROSS_COMPILE_ARCHITECTURE='x86_64'
CROSS_COMPILE_TRIPLET="${CROSS_COMPILE_ARCHITECTURE}-unknown-${CROSS_COMPILE_SYSTEM}"
CROSS_COMPILE_SYSROOT="${VENTI_HOME}/${CROSS_COMPILE_TRIPLET}"

CMAKE_TOOLCHAIN_FILE="${VENTI_HOME}/build/cmake/${CROSS_COMPILE_TRIPLET}.cmake"

CC="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
AR="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
OBJDUMP="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objdump"
READELF="${VENTI_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export \
	CROSS_COMPILE_TRIPLET \
	CROSS_COMPILE_SYSTEM \
	CROSS_COMPILE_ARCHITECTURE \
	CROSS_COMPILE_SYSROOT \
	CMAKE_TOOLCHAIN_FILE \
	CC \
	CXX \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	OBJDUMP \
	READELF

[[ "${kopt}" = *e*  ]] || set +e
[[ "${kopt}" = *u*  ]] || set +u
